./ovface -m_fd ./models/face-detection-0104.xml \
         -m_lm ./models/landmarks-regression-retail-0009.xml \
         -m_reid ./models/model-r50-am-lfw-0000.xml \
         -fg ./share/faces_gallery.json \
         -i ./share/004.mp4 \
         -o ./share/004_slow.mp4 \
         -t_reid 0.62 \
         -t_fd 0.9 \
         -di 4 \
         -ri  8 \
         -cg